//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirCoef
    {
        public long Curve { get; set; }
        public Nullable<double> creHT { get; set; }
        public Nullable<double> reexpHT { get; set; }
        public Nullable<double> creDP { get; set; }
        public Nullable<double> reexpDP { get; set; }
    }
}
