//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BaroczyVoidFraction
    {
        public Nullable<double> I0 { get; set; }
        public Nullable<double> I1 { get; set; }
        public Nullable<double> I2 { get; set; }
        public Nullable<double> I3 { get; set; }
        public Nullable<double> I4 { get; set; }
        public Nullable<double> I5 { get; set; }
        public Nullable<double> I6 { get; set; }
        public long id { get; set; }
    }
}
